jaksim/Dockerfile, jaksim/build.gradle, jaksim/src/main/java/org/sopt/jaksim/global/config/RedisConfig.java, jaksim/src/main/java/org/sopt/jaksim/user/domain/RefreshToken.java, jaksim/src/main/java/org/sopt/jaksim/user/repository/RedisTokenRepository.java
https://github.com/jaksim-us/Jaksim-Server/blob/178f6652fd21431c0684db3c5be5eaaf4b47e86e/jaksim/src/main/java/org/sopt/jaksim/user/domain/RefreshToken.java#L11-L27
- `timeToLive` 속성으로 rtk의 유효 시간을 2주로 설정했습니다.
- `@Indexed` 어노테이션을 사용해 Redis에서 효율적인 검색을 할 수 있도록 했습니다.
https://github.com/jaksim-us/Jaksim-Server/blob/178f6652fd21431c0684db3c5be5eaaf4b47e86e/jaksim/src/main/java/org/sopt/jaksim/user/repository/RedisTokenRepository.java#L8-L10
- `CrudRepository` 를 상속받아 CRUD 작업을 할 수 있도록 했습니다.
https://github.com/jaksim-us/Jaksim-Server/blob/178f6652fd21431c0684db3c5be5eaaf4b47e86e/jaksim/src/main/java/org/sopt/jaksim/global/config/RedisConfig.java#L13-L36
- yaml 파일에 작성된 redis host, port 값을 주입했습니다.
- `RedisConnectionFactory` 는 Redis와의 연결을 생성하고 관리하는 팩토리 인터페이스입니다. `LettuceConnectionFactory`를 사용하여 Redis …
=> Feat [#8] Redis 관련 클래스 정의

jaksim/build.gradle, jaksim/src/main/java/org/sopt/jaksim/global/common/Constants.java, jaksim/src/main/java/org/sopt/jaksim/global/common/HealthCheckController.java, jaksim/src/main/java/org/sopt/jaksim/global/common/LoggingFilter.java, jaksim/src/main/java/org/sopt/jaksim/global/config/SwaggerConfig.java, jaksim/src/main/java/org/sopt/jaksim/user/api/UserApi.java
https://github.com/jaksim-us/Jaksim-Server/blob/7a1e414be5559e5f4946b48edca1a33005c26208/jaksim/src/main/java/org/sopt/jaksim/global/common/Constants.java#L3-L6
- 상수들을 모아놓는 클래스입니다.
https://github.com/jaksim-us/Jaksim-Server/blob/7a1e414be5559e5f4946b48edca1a33005c26208/jaksim/src/main/java/org/sopt/jaksim/global/common/LoggingFilter.java#L24-L106
- 로깅을 더 깔끔하게 보기 위해 Request IP, Body를 나눠서 정리해주는 LoggingFilter를 추가했습니다.
https://github.com/jaksim-us/Jaksim-Server/blob/7a1e414be5559e5f4946b48edca1a33005c26208/jaksim/src/main/java/org/sopt/jaksim/global/config/SwaggerConfig.java#L9-L23
- Swagger의 메인 페이지와 설명칸을 추가했습니다.
- SpringDoc 라이브러리를 사용했습니다.
https://github.com/jaksim-us/Jaksim-Server/blob/7a1e414be5559e5f4946b48edca1a33005c26208/jaksim/src/main/java/org/sopt/jaksim/user/api/UserApi.java#L15-L54 …
=> Feat [#10] Swagger 세팅

.idea/.gitignore, .idea/Jaksim-Server.iml, .idea/gradle.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, jaksim/build.gradle, jaksim/src/main/java/org/sopt/jaksim/auth/PrincipalHandler.java, jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/auth/UserAuthentication.java, jaksim/src/main/java/org/sopt/jaksim/auth/filter/CustomAccessDeniedHandler.java, jaksim/src/main/java/org/sopt/jaksim/auth/filter/CustomJwtAuthenticationEntryPoint.java, jaksim/src/main/java/org/sopt/jaksim/auth/filter/JwtAuthenticationFilter.java, jaksim/src/main/java/org/sopt/jaksim/global/common/jwt/JwtTokenProvider.java, jaksim/src/main/java/org/sopt/jaksim/global/common/jwt/JwtValidationType.java, jaksim/src/main/java/org/sopt/jaksim/global/message/ErrorMessage.java, jaksim/src/main/java/org/sopt/jaksim/user/api/UserApiController.java, jaksim/src/main/java/org/sopt/jaksim/user/dto/request/UserSignInRequest.java, jaksim/src/main/java/org/sopt/jaksim/user/dto/response/UserSignInResponse.java, jaksim/src/main/java/org/sopt/jaksim/user/service/UserService.java, jaksim/src/main/resources/application.yml
- 진행중이라 마지막에 설명 쓰겠슴니다....
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Prefix [#5] jwt 구현 진행중

jaksim/build.gradle, jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/global/common/S3Service.java, jaksim/src/main/java/org/sopt/jaksim/global/config/AwsConfig.java, jaksim/src/main/java/org/sopt/jaksim/user/api/UserApiController.java
-  
<br>
- White List 수정했습니다.
<br>
- build.gradle 의존성 추가했습니다.
- CD_APPLICATION 수정했습니다 (S3 까지)
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Feat [#20] Amazon S3 설정 & 시큐리티 설정 클래스 수정

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/category/domain/Category.java, jaksim/src/main/java/org/sopt/jaksim/category/domain/CategoryTask.java, jaksim/src/main/java/org/sopt/jaksim/global/config/RedisConfig.java, jaksim/src/main/java/org/sopt/jaksim/mset/domain/CategoryMset.java, jaksim/src/main/java/org/sopt/jaksim/mset/domain/Mset.java, jaksim/src/main/java/org/sopt/jaksim/mset/domain/TaskMset.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/Task.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/TaskTimer.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/Todo.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/TodoTask.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/UserTimer.java, jaksim/src/main/java/org/sopt/jaksim/user/domain/Permission.java, jaksim/src/main/java/org/sopt/jaksim/user/domain/PermissionLevel.java, jaksim/src/main/java/org/sopt/jaksim/user/domain/User.java
기본 엔티티 클래스 (SQL, Redis) 작업 완료
같이 해서 따로 자세하게 안 적을게요 -!
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Feat [#22] 기본 엔티티 클래스 세팅

jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java, jaksim/src/main/java/org/sopt/jaksim/category/domain/Category.java, jaksim/src/main/java/org/sopt/jaksim/category/domain/CategoryTask.java, jaksim/src/main/java/org/sopt/jaksim/category/dto/CategoryTaskLink.java, jaksim/src/main/java/org/sopt/jaksim/category/dto/FilteredResourceResponse.java, jaksim/src/main/java/org/sopt/jaksim/category/repository/CategoryRepository.java, jaksim/src/main/java/org/sopt/jaksim/category/repository/CategoryTaskRepository.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryTaskFacade.java, jaksim/src/main/java/org/sopt/jaksim/global/common/DateUtil.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/Todo.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
https://github.com/morib-in/Jaksim-Server/blob/3e54f161373bc4b84b32c7fb044f521abbbbb1aa/jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java#L35-L40
- 구간에 해당하는 카테고리, 태스크 조회를 위해 @RequestParam으로 startDate, endDate를 받고 LocalDate 형태로 변환을 위해 @DateTimeFormat을 사용했습니다.
- Category와 Task Service 레이어를 동시에 사용하기 때문에 Facade 레이어를 추가했습니다.
https://github.com/morib-in/Jaksim-Server/blob/3e54f161373bc4b84b32c7fb044f521abbbbb1aa/jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryTaskFacade.java#L25-L58
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Feat [#30] 구간에 해당하는 카테고리, 태스크 조회 API 구현

.idea/modules.xml, jaksim/src/main/java/org/sopt/jaksim/category/domain/CategoryTask.java, jaksim/src/main/java/org/sopt/jaksim/global/common/BaseTimeEntity.java, jaksim/src/main/java/org/sopt/jaksim/task/api/TaskApiController.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/Task.java, jaksim/src/main/java/org/sopt/jaksim/task/dto/TaskCreateRequest.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
https://github.com/morib-in/Jaksim-Server/blob/245e891ffdc62582a4647f0c58994268083bc868/jaksim/src/main/java/org/sopt/jaksim/task/api/TaskApiController.java#L42-L48
- /api/v1/categories/{categoryId}" 경로에 작업 생성 데이터 보내면, 해당 카테고리 ID에 맞춰 새 태스크을 생성하고 성공 메시지를 반환
- categoryId 변수로 추출
- TaskCreateRequest 객체를 반환
https://github.com/morib-in/Jaksim-Server/blob/245e891ffdc62582a4647f0c58994268083bc868/jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java#L34-L49
- 주어진 카테고리 ID와 작업 생성 요청 정보를 사용하여 태스크, 카테고리 객체 생성, 데이터베이스에 저장
https://github.com/morib-in/Jaksim-Server/blob/245e891ffdc62582a4647f0c58994268083bc868/jaksim/src/main/java/org/sopt/jaksim/task/dto/TaskCreateRequest.java#L5-L12
https://github.com/morib-in/Jaksim-Server/blob/245e891ffdc62582a4647f0c58994268083bc868/jaksim/src/main/java …
=> Feat[#32] 태스크생성 API 구현

jaksim/build.gradle, jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java, jaksim/src/main/java/org/sopt/jaksim/category/dto/CategoryCheckResponse.java, jaksim/src/main/java/org/sopt/jaksim/category/repository/CategoryRepository.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java
https://github.com/morib-in/Jaksim-Server/blob/680cbcbd02f16687dda85d6882a0031079fabfec/jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java#L44-L48
https://github.com/morib-in/Jaksim-Server/blob/680cbcbd02f16687dda85d6882a0031079fabfec/jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java#L80-L92
https://github.com/morib-in/Jaksim-Server/blob/680cbcbd02f16687dda85d6882a0031079fabfec/jaksim/src/main/java/org/sopt/jaksim/category/repository/CategoryRepository.java#L20-L21
https://github.com/morib-in/Jaksim-Server/blob/680cbcbd02f16687dda85d6882a0031079fabfec/jaksim/src/main/java/org/sopt/jaksim/category/dto/CategoryCheckResponse.java#L1-L13
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix[#37] 사용자 모든 카테고리 조회

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java, jaksim/src/main/java/org/sopt/jaksim/category/dto/CategoryMsetLinkResponse.java, jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryMsetFacade.java, jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java, jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApiController.java, jaksim/src/main/java/org/sopt/jaksim/mset/repository/CategoryMsetRepository.java, jaksim/src/main/java/org/sopt/jaksim/mset/service/CategoryMsetService.java, jaksim/src/main/java/org/sopt/jaksim/mset/service/MsetService.java, jaksim/src/main/java/org/sopt/jaksim/task/api/TimerApiController.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/Todo.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/TodoTask.java, jaksim/src/main/java/org/sopt/jaksim/task/domain/UserTimer.java, jaksim/src/main/java/org/sopt/jaksim/task/dto/StartTimerRequest.java, jaksim/src/main/java/org/sopt/jaksim/task/dto/TaskInTodoCard.java, jaksim/src/main/java/org/sopt/jaksim/task/dto/TodoCardResponse.java, jaksim/src/main/java/org/sopt/jaksim/task/repository/TaskTimerRepository.java, jaksim/src/main/java/org/sopt/jaksim/task/repository/TodoRepository.java, jaksim/src/main/java/org/sopt/jaksim/task/repository/TodoTaskRepository.java, jaksim/src/main/java/org/sopt/jaksim/task/repository/UserTimerRepository.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskTimerService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TodoService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TodoTaskService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/UserTimerService.java, jaksim/src/main/java/org/sopt/jaksim/user/api/UserApi.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Feat [#39] 홈뷰, URL Fetch, 모립세트 불러오기 API

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#46] CORS 코드 수정

jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
WebSecurityConfig 포트, path 수정
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #49
=> Fix [#49] cors 코드수정

jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
origin, method 수정
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #51
=> Fix [#51] cors 코드 수정

jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
corsFilterRegistrationBean의 cors.addAllowedMethod 추가
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #53
=> Fix [#53] cors 코드 수정

jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #55
=> Fix [#55] corsFilterRegistrationBean 삭제

jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
allowedCredentials 제외
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#57] cors 코드 수정

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
securityfilterchain에 cors 설정
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #59
=> Fix [#59] cors 코드 수정

jaksim/src/main/java/org/sopt/jaksim/auth/filter/JwtAuthenticationFilter.java, jaksim/src/main/java/org/sopt/jaksim/global/common/HealthCheckController.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#61] spring cors 수정

jaksim/src/main/java/org/sopt/jaksim/auth/filter/CustomAccessDeniedHandler.java
throw forbidden 주석처리
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#63] CustomAccessDeniedHandler 수정

jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
addCorsMappings allowedOriginPatterns로 변경
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#65] spring cors 수정

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#67] authorization set 제외

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#69] SecurityConfig에서 cors 제외

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#71] Spring Security에 CorsUtils isPreFlightRequest 추가

jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#73] credential 제외

jaksim/build.gradle, jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#75] cors 관련 수정

jaksim/src/main/java/org/sopt/jaksim/socket/config/SocketIoConfig.java, jaksim/src/main/java/org/sopt/jaksim/socket/config/SocketIoServerLifeCycle.java, jaksim/src/main/java/org/sopt/jaksim/socket/config/SocketModule.java, jaksim/src/main/java/org/sopt/jaksim/socket/controller/MessageController.java, jaksim/src/main/java/org/sopt/jaksim/socket/controller/SocketIOController.java, jaksim/src/main/java/org/sopt/jaksim/socket/dto/WebSocketRequest.java, jaksim/src/main/java/org/sopt/jaksim/socket/dto/WebSocketResponse.java, jaksim/src/main/java/org/sopt/jaksim/socket/message/Message.java, jaksim/src/main/java/org/sopt/jaksim/socket/message/MessageType.java, jaksim/src/main/java/org/sopt/jaksim/socket/repository/RedisSocketMessageRepository.java, jaksim/src/main/java/org/sopt/jaksim/socket/service/MessageService.java, jaksim/src/main/java/org/sopt/jaksim/socket/service/SocketService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#75] socket

jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApi.java, jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java, jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApi.java, jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApiController.java, jaksim/src/main/java/org/sopt/jaksim/task/api/TaskApi.java, jaksim/src/main/java/org/sopt/jaksim/task/api/TaskApiController.java, jaksim/src/main/java/org/sopt/jaksim/task/api/TimerApi.java, jaksim/src/main/java/org/sopt/jaksim/task/api/TimerApiController.java, jaksim/src/main/java/org/sopt/jaksim/user/api/SocialLoginTempController.java
https://github.com/morib-in/Jaksim-Server/blob/497cf53d9be7b7e374d36ff6d57795c8739b50e3/jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApi.java#L22-L50
https://github.com/morib-in/Jaksim-Server/blob/497cf53d9be7b7e374d36ff6d57795c8739b50e3/jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApi.java#L54-L94
https://github.com/morib-in/Jaksim-Server/blob/497cf53d9be7b7e374d36ff6d57795c8739b50e3/jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApi.java#L95-L125
https://github.com/morib-in/Jaksim-Server/blob/497cf53d9be7b7e374d36ff6d57795c8739b50e3/jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApi.java#L13-L48
https://github.com/morib-in/Jaksim-Server/blob/497cf53d9be7b7e374d36ff6d57795c8739b50e3/jaksim/src/main/java/org/sopt/jaksim/task/api/TaskApi.java#L19-L50 …
=> Fix[#45] 스웨거 전체 적용

jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/global/common/HealthCheckController.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #79
=> Fix [#79] Spring cors 코드 제외

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/auth/WebSecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#81] nginx + springboot cors 동시설정

jaksim/src/main/java/org/sopt/jaksim/user/api/SocialLoginTempController.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #85
=> Fix [#85] SocialLoginTempController return문 수정

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #87
=> Fix [#87] white-list 전부 열기

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#87] white-list 정확한 경로로 지정

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#91] white-list 와일드카드 아예 제외

jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApi.java, jaksim/src/main/java/org/sopt/jaksim/global/config/SwaggerConfig.java, jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApi.java, jaksim/src/main/java/org/sopt/jaksim/task/api/TaskApi.java, jaksim/src/main/java/org/sopt/jaksim/task/api/TimerApi.java, jaksim/src/main/java/org/sopt/jaksim/user/api/UserApi.java
https://github.com/morib-in/Jaksim-Server/blob/f9bd9b0b30dd04d0f0d7e17d6b4afbfa48b2bf19/jaksim/src/main/java/org/sopt/jaksim/global/config/SwaggerConfig.java#L22-L23
https://github.com/morib-in/Jaksim-Server/blob/f9bd9b0b30dd04d0f0d7e17d6b4afbfa48b2bf19/jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApi.java#L24
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix[#93] 스웨거 오류 해결

jaksim/src/main/java/org/sopt/jaksim/auth/SecurityConfig.java, jaksim/src/main/java/org/sopt/jaksim/global/message/ErrorMessage.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskTimerService.java, jaksim/src/main/java/org/sopt/jaksim/user/api/SocialLoginTempController.java, jaksim/src/main/java/org/sopt/jaksim/user/api/UserApiController.java, jaksim/src/main/java/org/sopt/jaksim/user/facade/UserFacade.java, jaksim/src/main/java/org/sopt/jaksim/user/service/UserService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#94] 로컬단 회원가입 api 수정

jaksim/src/main/java/org/sopt/jaksim/user/service/UserService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#97] redis rtk 코드 임시 주석처리

jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java, jaksim/src/main/java/org/sopt/jaksim/mset/service/MsetService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskTimerService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TodoService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TodoTaskService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/UserTimerService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#99] principal 세팅 제외

jaksim/src/main/java/org/sopt/jaksim/category/dto/CategoryTaskLink.java, jaksim/src/main/java/org/sopt/jaksim/category/dto/FilteredResourceResponse.java, jaksim/src/main/java/org/sopt/jaksim/category/dto/TaskWithTaskTimer.java, jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/UserTimerService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#101] 홈뷰 조회 API 수정

jaksim/Dockerfile
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> [Fix] Dockerfile 수정

jaksim/Dockerfile
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> [Fix] Dockerfile 수정 (#104)

jaksim/src/main/java/org/sopt/jaksim/category/domain/Category.java, jaksim/src/main/java/org/sopt/jaksim/category/domain/CategoryTask.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#107] @Table 제외

jaksim/src/main/java/org/sopt/jaksim/category/dto/CategoryCreateRequest.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#109] category create 수정

jaksim/src/main/java/org/sopt/jaksim/category/repository/CategoryTaskRepository.java, jaksim/src/main/java/org/sopt/jaksim/task/dto/TaskInTodoCard.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TodoService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#111] 할일카드에 필요 데이터 추가 후 정렬

jaksim/src/main/java/org/sopt/jaksim/category/dto/TaskWithTaskTimer.java, jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#113] 홈뷰 isComplete response에 추가

jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
task, category
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#115] 홈뷰 null handling

jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java, jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryMsetFacade.java, jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java, jaksim/src/main/java/org/sopt/jaksim/category/repository/CategoryRepository.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryService.java, jaksim/src/main/java/org/sopt/jaksim/category/service/CategoryTaskService.java, jaksim/src/main/java/org/sopt/jaksim/mset/service/CategoryMsetService.java, jaksim/src/main/java/org/sopt/jaksim/mset/service/MsetService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Feat [#117] 카테고리 삭제 API 구현

jaksim/src/main/java/org/sopt/jaksim/global/common/HealthCheckController.java
- 헬스체크 API를 /profile로 대체했습니다.
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Fix [#119] 헬스체크 API 수정

jaksim/src/main/java/org/sopt/jaksim/global/exception/GlobalExceptionHandler.java, jaksim/src/main/java/org/sopt/jaksim/global/message/ErrorMessage.java, jaksim/src/main/java/org/sopt/jaksim/user/service/UserService.java
- 
<br>
- 
<br>
- 
<br>
어떤 변경 사항인가요?
<br>
Resolved #이슈번호
=> Feat [#121] 에러 핸들링 코드 추가

jaksim/src/main/java/org/sopt/jaksim/mset/domain/TaskMset.java
closes #129 
TaskMset에 @Entity 어노테이션 추가했습니다.
=> Fix [#129] TaskMset 어노테이션 추가

jaksim/src/main/java/org/sopt/jaksim/category/facade/CategoryTaskFacade.java
- closes #147 
홈뷰 전체조회 시, taskId를 내림차순 기준으로 정렬하는 코드를 추가했습니다.
=> Fix [#147] 홈뷰 전체조회 API 태스크 Id 내림차순으로 정렬

jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApi.java, jaksim/src/main/java/org/sopt/jaksim/category/api/CategoryApiController.java, jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApi.java, jaksim/src/main/java/org/sopt/jaksim/mset/api/MsetApiController.java
- closes #143 
카테고리 삭제, 특정 태스크의 모립세트 불러오기 api에 대해 스웨거 적용했습니다 !
=> Fix[#143] 스웨거 추가 적용

jaksim/src/main/java/org/sopt/jaksim/task/repository/TaskTimerRepository.java, jaksim/src/main/java/org/sopt/jaksim/task/repository/TodoTaskRepository.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TaskTimerService.java, jaksim/src/main/java/org/sopt/jaksim/task/service/TodoTaskService.java
- closes #149 
TaskTimer 생성 시, DB에서 확인하는 검증 로직 추가했습니다.
=> Bug [#149] NonUniqueResultException
